### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by adriandrozdz** [coderello/laravel-passport-social-grant#10]
How can I make it work with PHP 7.1?

`Using version ^2.0 for coderello/laravel-passport-social-grant`

``` 
Problem 1
    - illuminate/auth 5.9.x-dev requires php ^7.2 -> your PHP version (7.1.12) does not satisfy that requirement.
```

**Comment by hivokas** [comment]
That's a requirement of `illuminate/auth`, not `coderello/laravel-passport-social-grant`
