### ISSUE TITLE
Is not instantiable while building Laravel\Passport\Http\Controllers\AccessTokenController

### ISSUE THREAD

**Issue by nahojj** [coderello/laravel-passport-social-grant#12]
I've got this error

`"Target [Coderello\SocialGrant\Resolvers\SocialUserResolverInterface] is not instantiable while building [Laravel\Passport\Http\Controllers\AccessTokenController]."`

any clue?

**Comment by nemwiper** [comment]
Had the same issue, I was forgetting to reference classes in the AppServiceProvider

`use App\Resolvers\SocialUserResolver;`
`use Coderello\SocialGrant\Resolvers\SocialUserResolverInterface;`

Those two lines of code!
Of course you have to specify the right path of your version of the SocialUserResolver in your project!

**Comment by nahojj** [comment]
@nemwiper It's so funny you said that it was exactly my problem!! I didn't reference the classes in the provider and it makes sense that it will not work then.. So stupid of me, hah! Thanks anyway :)

**Comment by nemwiper** [comment]
I'm glad that it kinda helped! :D

**Comment by Azghour-Saad** [comment]
Thanks a lot @nemwiper !!
