### ISSUE TITLE
unsupported_grant_type

### ISSUE THREAD

**Issue by Royvandenbroek** [coderello/laravel-passport-social-grant#15]
Hi guys,

I'm trying to get this to work but I keep getting:

```
{
    "error": "unsupported_grant_type",
    "error_description": "The authorization grant type is not supported by the authorization server.",
    "hint": "Check that all required parameters have been provided",
    "message": "The authorization grant type is not supported by the authorization server."
}
```

When sending this request:
```
grant_type:social
client_id:5
client_secret:***
provider:google
access_token:***
```
I'm able to get the password-grant to work on the same endpoint. Tried clearing the cache. Any idea where to start investigating this issue?

**Comment by Royvandenbroek** [comment]
I managed to solve it, I configured it wrong in my composer file. Sorry.

**Comment by bertdida** [comment]
Hey @Royvandenbroek , I'm getting the same error. Can you provide a guide how you managed to solve this.
