### ISSUE TITLE
I can't set scopes in the Oauth token table.

### ISSUE THREAD

**Issue by canemarcovaro** [coderello/laravel-passport-social-grant#20]
Hi comunity!  The problem is when i want set a default scope in a new token thats come from google. I read the documentation from Socialite and and I don't know why it doesn't work. The insertion in the database is done correctly but does not set the scope in the DB.

**Comment by canemarcovaro** [comment]
my code: 
  $providerUser = Socialite::driver($provider)->scopes(['normal-user'])->userFromToken($accessToken);

**Comment by hivokas** [comment]
I believe this issue is not related to `coderello/laravel-passport-social-grant`.
