### ISSUE TITLE
Google grant - invalid_credentials

### ISSUE THREAD

**Issue by andrewl94** [coderello/laravel-passport-social-grant#33]
Receiving this response, even with correct configuration:

error: "invalid_credentials"
error_description: "The user credentials were incorrect."
message: "The user credentials were incorrect."

The same token are being able to return the user data if directly on frontend.
Other issues like this one are closed even without a solution.

**Comment by ankurk91** [comment]
Please refer to this example

https://github.com/coderello/laravel-passport-social-grant/issues/23#issuecomment-627121749

Please check your Google credentials as well.
