### ISSUE TITLE
Invalid credentials.

### ISSUE THREAD

**Issue by c-karaolis** [coderello/laravel-passport-social-grant#36]
I have checked time and time again and it seems I've done everything correctly. I double checked with google's console 100 times and my credentials are correct.

I am using postman for the post request to /oauth/token . The response i am getting is 
![image](https://user-images.githubusercontent.com/27203568/92362679-020ab300-f0f9-11ea-872e-68de7d6c29fe.png)

 [Issue#23 ](https://github.com/coderello/laravel-passport-social-grant/issues/23 )did not help so please don't link me there too. 

Edit: I have also tried both x-www-form-urlencoded and plain form-data, both with the same error.

**Comment by ankurk91** [comment]
Try to add `dump()` statement inside your `vendor/laravel/socialte`, the file where php is calling google server, see what you get from server.

There is nothing i can help you in this issue.

**Comment by muhammedjailam** [comment]
The readme must be updated to support the latest updates. 

class SocialUserResolver implements SocialUserResolverInterface
{
    /**
     * Resolve user by provider credentials.
     */
    public function resolveUserByProviderCredentials(string $provider, string $accessToken): ?Authenticatable
    {
         $response = Socialite::driver($provider)->getAccessTokenResponse($accessToken);

        $token = Arr::get($response, 'access_token');

        $oauth_user = Socialite::driver($provider)->userFromToken($token);
        
        return $this->findOrCreateUser($provider, $providerUser);
    }
    
    protected function findOrCreateUser(string $provider, ProviderUser $providerUser): ?Authenticatable
    {
        // todo your logic here      
        // $email = $providerUser->getEmail();
    }
}
