### ISSUE TITLE
get access_token

### ISSUE THREAD

**Issue by xx1196** [coderello/laravel-passport-social-grant#43]
Hi, i need get the access token in ionic angular app, but i dont know how get this acces token, for example in google need open a new window with select the account, but not have any idea, tanks

**Comment by ankurk91** [comment]
This package has nothing to do with angular.

I can only share laravel backend example

https://github.com/ankurk91/laravel-passport-socialite-example

**Comment by xx1196** [comment]
@ankurk91 i understand the backend flow, i can see in the postman collectio you send the access_token, i need get this access token from the reactjs app, vuejs or ionic app. Very tanks for the example.
