### ISSUE TITLE
Support for Laravel Passport v11

### ISSUE THREAD

**Issue by goppi0** [coderello/laravel-passport-social-grant#47]
" - coderello/laravel-passport-social-grant 3.0.4 requires laravel/passport ^10.2.2 -> found laravel/passport[v10.2.2, ..., 10.x-dev] but it conflicts with your root composer.json require (^11.3)."

Will you support Passport v11 or is there an alternative you know off?

Thanks

**Comment by ankurk91** [comment]
Thanks for reminder, i will be working on adding support soon.
