### ISSUE TITLE
Help needed with SocialiteProviders using OAuth1

### ISSUE THREAD

**Issue by 4levels** [coderello/laravel-passport-social-grant#7]
Hi there,

Is there a way to use this with Providers that don't support OAuth2 (like Flickr)?
Authentication with Socialite works, but the method `userFromToken` is not available in the OAuth1 AbstractProvider, since OAuth1 requires a secret as well, hence the `userFromTokenAndSecret` method.

Do you have any experience with OAuth1 providers?

Kind regards

**Comment by hivokas** [comment]
Hi 👋
Sorry for the late response.
You can get secret from the config and use it inside your resolver.

**Comment by steve228uk** [comment]
@hivokas Unfortunately this isn't possible. OAuth1 providers require an `accessToken` and `accessTokenSecret`. This is *not* the `clientSecret`. 

As such, the body of the request to the API would look like the following

```
grant_type:social
client_id:1
client_secret:xxxxxxxxx
provider:twitter
access_token:xxxxxxxxxx
access_token_secret:xxxxxxxxxx
scope:
```

The `resolveUserByProviderCredentials` needs a third (nullable) parameter of `accessTokenSecret` adding to it. Then we can check if this is set and pass it to Socialite's `userFromTokenAndSecret` instead.
